function insRow(){document.getElementById("addChildrenLink").style.display="none";document.getElementById("abExtras0").style.display="";document.getElementById("error0").style.display="";document.getElementById("abExtras1").style.display="";document.getElementById("error1").style.display="";document.getElementById("abExtras2").style.display="";
document.getElementById("error2").style.display="";document.getElementById("abExtras3").style.display="";document.getElementById("error3").style.display="";}function populatePrsnlizeDropDown(a){var g=false;if(a.name!="registration1"){var s=a.dueChild0Name.value;if(s.length==0){if((a.dueChild0birthMonth.options[a.dueChild0birthMonth.selectedIndex].value!="")&&(a.dueChild0birthDay.options[a.dueChild0birthDay.selectedIndex].value.length!=0)&&(a.dueChild0birthYear.options[a.dueChild0birthYear.selectedIndex].value.length!=0)){s="Pregnancy";
}}var r=a.child0Name.value;var q=a.child1Name.value;var p="";var o="";var n="";var m="";var j="";var h="";var f="";var d="";var c=2;if(a.name=="editProfile"){g=a.checkedTryToCncve.checked;if(a.child2Name){p=a.child2Name.value;c=c+1;}if(a.child3Name){o=a.child3Name.value;c=c+1;}if(a.child4Name){n=a.child4Name.value;
c=c+1;}if(a.child5Name){m=a.child5Name.value;c=c+1;}if(a.addMorechild0Name){j=a.addMorechild0Name.value;}if(a.addMorechild1Name){h=a.addMorechild1Name.value;}if(a.addMorechild2Name){f=a.addMorechild2Name.value;}if(a.addMorechild3Name){d=a.addMorechild3Name.value;}}else{j=a.addMorechild0Name.value;h=a.addMorechild1Name.value;
f=a.addMorechild2Name.value;d=a.addMorechild3Name.value;}var b=a.prsnlize;var l=b.options.length;var e=b.options[b.selectedIndex].value;var k=b.options[b.selectedIndex].text;for(var c=b.options.length-1;c>=0;c--){b[c]=null;}l=b.options.length;b.length=1;b[l].value="-1";b[l].text="Please Select one";l++;
if(g){l=l+1;b.length=l;b[l-1].value="ttc";b[l-1].text="Trying to conceive";}if(s.length!=0){l=l+1;b.length=l;b[l-1].value=0;b[l-1].text=s;}if(r.length!=0){l=l+1;b.length=l;b[l-1].value=1;b[l-1].text=r;}if(q.length!=0){l=l+1;b.length=l;b[l-1].value=2;b[l-1].text=q;}if(a.name=="editProfile"){if(p.length!=0){l=l+1;
b.length=l;b[l-1].value=3;b[l-1].text=p;}if(o.length!=0){l=l+1;b.length=l;b[l-1].value=4;b[l-1].text=o;}if(n.length!=0){l=l+1;b.length=l;b[l-1].value=5;b[l-1].text=n;}if(m.length!=0){l=l+1;b.length=l;b[l-1].value=6;b[l-1].text=m;}}if(j.length!=0){l=l+1;b.length=l;b[l-1].value=c+1;b[l-1].text=j;}if(h.length!=0){l=l+1;
b.length=l;b[l-1].value=c+1;b[l-1].text=h;}if(f.length!=0){l=l+1;b.length=l;b[l-1].value=c+1;b[l-1].text=f;}if(d.length!=0){l=l+1;b.length=l;b[l-1].value=c+1;b[l-1].text=d;}for(i=0;i<b.options.length;i++){if(b.options[i].value==e){b.options[i].selected="true";}}}}function checkDropDownOptions(a,b){if(b.options.length<=1){}else{if(a.dueChild0Name.value.length==0){if((a.dueChild0birthMonth.options[a.dueChild0birthMonth.selectedIndex].value!="")&&(a.dueChild0birthDay.options[a.dueChild0birthDay.selectedIndex].value.length!=0)&&(a.dueChild0birthYear.options[a.dueChild0birthYear.selectedIndex].value.length!=0)){populatePrsnlizeDropDown(a);
}}}}function checkDisp(a){RegistrationService.checkDisplayName(a,dispCallback);}function dispCallback(a){if(a[0].toString()=="false"){DWRUtil.setValue("displayName-error","&#149;&nbsp;Display Name already exists. Suggested display name is "+a[1]);$("#displayName").css("color","red");}else{DWRUtil.setValue("displayName-error","");
$("#displayName").css("color","black");}}function emailCallback(resu){if(resu[0].toString()=="true"){DWRUtil.setValue("email-error","&#149;&nbsp;Email already exists");$("#email").css("color","red");var remote=null;text="<p><a target='main' href='/common/profile/login1.jsp' onClick='setTimeout("+'"'+"window.close()"+'"'+",100)'>Click here to Login!</a></p>";
remote=window.open("","LoginWindow","width=300,height=300,screenX=100,screenY=200,top=50,left=80,resizable=yes,scrollbars=yes");with(remote.document){open();write(text);close();}}else{DWRUtil.setValue("email-error","");$("#email").css("color","black");}}function populateChildMonth(a,b,c){if(a.name=="registration"){if(b.name=="birthMonth"){document.registration.child0birthMonth.options[c].selected="true";
}else{if(b.name=="dueMonth"){document.registration.dueChild0birthMonth.options[c].selected="true";}}}}function populateChildDay(b,c,a){if(b.name=="registration"){if(c.name=="birthDay"){document.registration.child0birthDay.options[a].selected="true";}else{if(c.name=="dueDay"){document.registration.dueChild0birthDay.options[a].selected="true";
}}}}function populateChildYear(b,c,a){if(b.name=="registration"){if(c.name=="birthYear"){document.registration.child0birthYear.selectedIndex=c.selectedIndex;}else{if(c.name=="dueYear"){document.registration.dueChild0birthYear.selectedIndex=c.selectedIndex;}}}}function requiredChildInfo(a,b){if(a.name=="registration"){if(b.checked){document.getElementById("reqText").style.display="";
document.getElementById("reqNameText").style.display="";document.getElementById("reqBirthText").style.display="";document.getElementById("reqSexText").style.display="";}}}