/*
 Copyright 2008-2013 Adometry, Inc.
*/
var DMTRY=DMTRY||{};
(function(){try{DMTRY.namespace=function(a){var c=DMTRY;a=a.split(".");var d;"DMTRY"===a[0]&&(a=a.slice(1));for(d=0;d<a.length;d++)"undefined"===typeof c[a[d]]&&(c[a[d]]={}),c=c[a[d]];return c};var l=DMTRY.namespace("ADO"),B=!1,C=new function(a){var c=[];this.checkpoint=function(d){for(d=d||-1;c.length>=a;)c.shift();c.push(d)};this.toString=function(){return"track:"+c.toString()}}(50),f=C.checkpoint,s={dl:{desc:"DataLogix",propName:"ddl",actionCode:"ddl",logMutator:function(a,c){return a.replace(k.HOSTNAME,
"adometry.nexac.com/dlp")}}},y=new function(){var a=this;a.hasFocus=!0;a.onblur=function(){a.hasFocus=!1};a.onfocus=function(){a.hasFocus=!0}},g=function(a,c,d,e){this.type=a;this.description=c;this.requiredProps=d;this.appendCustomValues=e;this.logMutator=null};g.DEFINED={IMP:new g("i","Imp",["echo","sz"],!0),LOAD:new g("ol","Load","csync ds dsf if mbl ols sf sn sz ta tp vd x y".split(" ")),SEEN:new g("sn","Seen",["sn","ta","tp","vd"]),POST:new g("p","Post",["ta","tp","vd"])};g.DEFINED.IMP.logMutator=
function(a,c){var d=a;!1!==c.cookie&&(d=a.replace(k.HOSTNAME,k.HOSTNAME+"/redir"));return d};var D=[],x;for(x in s)if(s.hasOwnProperty(x)){var t=s[x];g.DEFINED[t.actionCode]=new g(t.actionCode,t.desc,[]);D.push(t.propName);null!=g.DEFINED[t.actionCode]&&(g.DEFINED[t.actionCode].logMutator=t.logMutator)}g.DEFINED.LOAD.requiredProps=D.concat(g.DEFINED.LOAD.requiredProps);l.Action=l.Action||g;var n=function(){this.scriptElement=null;this.protocol="http";this.dgVendors=[];this.position=this.adSize="";
this.csync=this.cookie=!0;this.echo="";this.passthru={};for(var a=n.INCOMING_PARAM_ORDER,c=0;c<a.length;c++)this[a[c]]=0};n.INCOMING_PARAM_ORDER="bid gid pid cid aid srcid advid".split(" ");n.isNumber=function(a){return!isNaN(parseFloat(a))&&isFinite(a)};n.loadActivator=function(a,c,d){c=c.toLowerCase();var e=null;if("csync"===c)0===Number(d)&&(a.csync=!1);else if("debug"===c)1===Number(d)&&(B=!0);else if("echo"===c)a.echo=d;else if("nc"===c)1===Number(d)&&(a.cookie=1===Number(d)?!1:!0);else if("pos"===
c)e=d.match(/(\w{2})$/i),null!=e&&(a.position=e[0]);else if("sz"===c)e=d.match(/(\d+x\d+)/),null!=e&&(a.adSize=e[0]);else for(var h in s)s.hasOwnProperty(h)&&c===h.toLowerCase()&&1===Number(d)&&a.dgVendors.push(h)};n.parseScriptUrl=function(a){f(1);for(var c=new n,d=document.getElementsByTagName("script"),e=RegExp(a),h,b=0;b<d.length;b++)if(h=d[b],a=h.src||"X",f("2:"+a),a=a.replace(/^\s\s*/,"").replace(/\s\s*$/,""),0==a.search(e)&&"undefined"==typeof h.ADO)return f(3),h.ADO=!0,e=a.indexOf(":"),h=
"http",0<e&&(h=a.substring(0,e)),c.scriptElement=d[b],c.protocol=h,d=a.replace(/^[^\?]+\??/,""),n.processQueryString(c,d),c};n.processQueryString=function(a,c){if(""!==c){for(var d=c.split("&"),e=1;e<d.length;e++){var h=d[e],b=h.indexOf("="),p;-1<b?(p=h.substring(0,b),h=decodeURIComponent(h.substring(b+1))):(p=h,h=null);n.passthruValidator(p)?a.passthru[p]=h:n.loadActivator(a,p,h)}e=d[0].split("_");p=n.INCOMING_PARAM_ORDER;if(3<=e.length){f(4);for(d=0;d<e.length&&d<p.length;d++)if(null!=e[d]&&""!=
e[d]){if("gid"===p[d]&&!n.isNumber(e[d]))throw Error("Invalid Campaign: "+e[d]);a[p[d]]=e[d]}}else throw Error("Script param error: "+d[0]);}};n.passthruValidator=function(a){return-1<a.search(/^cus\./)?!0:!1};var E=function(){var a={sf:!1};try{$sf&&$sf.ext&&(a.sf=!0)}catch(c){}this.isSafeFrame=function(){return a.sf};return this};l.AntennaManager=l.AntennaManager||{};l.AntennaManager.antennas=l.AntennaManager.antennas||[];l.AntennaManager.imageElems=l.AntennaManager.imageElems||[];l.AntennaManager.scriptElems=
l.AntennaManager.scriptElems||[];l.AntennaManager.create=function(a){f(20);if(null==a||!a.protocol||!a.bid||!a.gid||!a.pid||a&&"object"==typeof a&&a.constructor!=n)return null;var c=l.AntennaManager,d=k,e=c.antennas,c=c.imageElems,h=e.length,b=null,p=B?5:0;if(null==b){f(21);document.write('<img width="0" height="0" border="'+p+'" name="ADO_track_new">');var q=document.getElementsByName("ADO_track_new");0<q.length&&(b=q[0],b.name="ADO_track")}if(null==b&&(f(22),q=a.scriptElement,null!=q))try{b=document.createElement("img"),
b.name="ADO_track",b.width=0,b.height=0,b.border=p,q.parentNode.insertBefore(b,q)}catch(m){b=null}f(23);null!=b?(c[h]=b,e[h]=new d(a,g.DEFINED.IMP,h)):d.sendError(a,"noImage");f(24);return e[h]};l.AntennaManager.shutdownAntennas=function(){var a=l.AntennaManager.antennas;if(a&&0<a.length){var c;for(c=0;c<a.length;c++)a[c].sendResponse(g.DEFINED.POST),a[c].timerID&&(clearInterval(a[c].timerID),a[c].timerID=null)}};var v=function(){var a=this;a.isSupported=function(){return"undefined"!==typeof window.mozInnerScreenX?
!0:!1};a.getViewPortRect_Screen=function(){return c(!1)};a.getViewPortRect_Viewport=function(){return c(!0)};a.getFrameRect_Screen=function(){var a=window;return new r(a.mozInnerScreenX+a.innerWidth,a.mozInnerScreenY+a.innerHeight,a.mozInnerScreenX,a.mozInnerScreenY)};a.getFrameCoords_Viewport=function(){var c=a.getViewPortRect_Screen(),e=a.getFrameRect_Screen(),h=-1*c.left,c=-1*c.top,e=new r(e.right+h,e.bottom+c,e.left+h,e.top+c);return new u(e.left,e.top)};var c=function(a){var e=window,e={x1:e.screenX,
y1:e.screenY+80,x2:e.screenX+e.outerWidth,y2:e.screenY+e.outerHeight-10};if(null!=a&&a){a=-1*e.x1;var c=-1*e.y1,e={x1:e.x1+a,y1:e.y1+c,x2:e.x2+a,y2:e.y2+c}}return new r(e.x2,e.y2,e.x1,e.y1)};return a}(),u=function(a,c){this.x=a;this.y=c;return this};u.prototype.isDefined=function(){defined=!1;null!=this.x&&null!=this.y&&(defined=!0);return defined};u.prototype.isWithin=function(a){var c=!1;null!=a&&(a.isDefined()&&a.left<=this.x&&a.right>=this.x&&a.top<=this.y&&a.bottom>=this.y)&&(c=!0);return c};
var r=function(a,c,d,e){this.right=a;this.bottom=c;this.left=d||0;this.top=e||0;return this};r.prototype.isDefined=function(){var a=!1;null!=this.top&&(null!=this.right&&null!=this.bottom&&null!=this.left)&&(a=!0);return a};r.prototype.getArea=function(){var a=null;this.isDefined()&&(a=this.getWidth()*this.getHeight());return a};r.prototype.getHeight=function(){var a=null;this.isDefined()&&(a=this.bottom-this.top);return a};r.prototype.getWidth=function(){var a=null;this.isDefined()&&(a=this.right-
this.left);return a};r.prototype.intersects=function(a){if(this.isDefined()&&a.isDefined()&&(this.top<=a.top&&a.top<=this.bottom||this.top<=a.bottom&&a.bottom<=this.bottom||a.top<=this.top&&this.bottom<=a.bottom))if(this.left<=a.left&&a.left<=this.right||this.left<=a.right&&a.right<=this.right||a.left<=this.left&&this.right<=a.right)return!0;return!1};r.prototype.getIntersectingRect=function(a){return this.isDefined()&&a.isDefined()&&this.intersects(a)?new r(this.right<a.right?this.right:a.right,
this.bottom>a.bottom?a.bottom:this.bottom,this.left>a.left?this.left:a.left,this.top<a.top?a.top:this.top):null};r.prototype.percentIntersect=function(a){var c=0;if(this.isDefined()&&a.isDefined()){a=this.getIntersectingRect(a);a=null!=a?a.getArea():null;var d=this.getArea();null!=a&&null!=d&&(c=Math.round(100*(a/d)))}return c};var w=function(){var a=this,c={};a.frameClimbInfo=function(e){if(c.frameClimbInfo&&!e)return c.frameClimbInfo;var h={url:document.referrer,toTop:-1,friendLevel:0,inFrame:!1,
nonFriendlyPresent:!1,winStack:[]},b=window;e=0;for(var h=h.url,d=!1,q=!1,m=[],f=window,k=0;;f=f.parent,k++){m.push(f);if(20==k){k=-1;break}try{f.document?(b=f,e=k):q=!0}catch(l){q=!0}if(f==f.parent)break;else d=!0}f=k;try{h=e==f?b.location.href:b.document.referrer}catch(g){}b=a.isMobileAppEnvDetected();return h=c.frameClimbInfo={url:h,toTop:f,friendLevel:e,inFrame:d,nonFriendlyPresent:q||b,inMobile:b,winStack:m}};a.getDocumentRect=function(a,c){var b=new r(0,0,0,0),p=c&&"viewport"===c.toLowerCase()?
!0:!1;try{a=null==a?window:a;if(null!=a.innerWidth)b.right=a.innerWidth,b.bottom=a.innerHeight;else{var f=a.document;b.right=f.documentElement&&f.documentElement.clientWidth?f.documentElement.clientWidth:f.body.clientWidth||0;b.bottom=f.documentElement&&f.documentElement.clientHeight?f.documentElement.clientHeight:f.body.clientHeight||0}if(p){var m=d(a);b.left+=m.left;b.right+=m.left;b.top+=m.top;b.bottom+=m.top}}catch(k){}return b};a.getRootDocumentRect=function(e){var c=null,b=a.frameClimbInfo(),
d=b.winStack;b.nonFriendlyPresent||(c=a.getDocumentRect(d[d.length-1],e));return c};a.getLocationCoords=function(e,c,b,d){var f=new u(null,null),m=new u(0,0),k=window,l=a.frameClimbInfo(),g=a.getDocumentRect(k,"document");c=c&&"viewport"===c.toLowerCase()?!0:!1;var n;n=document.readyState&&"loaded"!=document.readyState&&"interactive"!=document.readyState&&"complete"!=document.readyState?!1:!0;if(!n||isNaN(g.getWidth())||isNaN(g.getHeight())||0>=g.getWidth()||0>=g.getHeight())return f;if(e){e=a.elemLocationInFrameViewPort(k,
e);k=new u(e.x,e.y);m.x+=e.x;m.y+=e.y;fixedElemFound=e.fixedElem;if(!k.isWithin(g))return f;if(l.inFrame)if(v.isSupported())l=v.getFrameCoords_Viewport(),m.x+=l.x||0,m.y+=l.y||0;else{if(l.nonFriendlyPresent)return f;for(f=0;f<l.winStack.length;f++)g=l.winStack[f],e=g.frameElement,null!=e&&(g=c?a.elemLocationInFrameViewPort(g.parent,e):a.elemLocationInFrame(g.parent,e),m.x+=g.x,m.y+=g.y)}l=80;c=-1;f=50;g=-1;e=Math.round;null!=d&&d.isDefined()&&(null!=d.getWidth()&&!isNaN(d.getWidth())&&(l=e(d.getWidth()/
2)),null!=d.getHeight()&&!isNaN(d.getHeight())&&(f=e(d.getHeight()/2)));null!=b&&(c=-1<b.indexOf("l")?1:-1,g=-1<b.indexOf("t")?1:-1);m.x+=c*l;m.y+=g*f}return m};a.getLocationPercentages=function(a,c,b){b=null!=b?b:!1;if(null!=a&&a.isDefined()&&null!=c&&c.isDefined())return a={x:Math.round(100*(a.x/c.getWidth())),y:Math.round(100*(a.y/c.getHeight()))},b&&(a.x=0>a.x?0:a.x,a.y=0>a.y?0:a.y),a};a.elemLocationInFrame=function(a,c){for(var b=c,d={x:0,y:0,fixedElem:!1};null!=b;){d.x+=b.offsetLeft+b.clientLeft;
d.y+=b.offsetTop+b.clientTop;if(null!=b.style){var f=b.style.position;if(null!=f&&"fixed"===f.toLowerCase()){d.fixedElem=!0;break}}b=b.offsetParent}return d};a.elemLocationInFrameViewPort=function(e,c){var b=a.elemLocationInFrame(e,c),f=null;b.fixedElem||(f=d(e),b.x-=f.left,b.y-=f.top);return b};a.isMobileAppEnvDetected=function(){var a=!1,c=window.screen;try{null!=c&&(0===c.width&&0===c.height&&0<c.colorDepth)&&(a=!0)}catch(b){}return a};var d=function(a){var c={left:0,top:0};c.left=a.pageXOffset||
a.document.body.scrollLeft||a.document.documentElement.scrollLeft||0;c.top=a.pageYOffset||a.document.body.scrollTop||a.document.documentElement.scrollTop||0;return c};return a}(),k=function(a,c,d){f(100);var e=k,h=l.AntennaManager,b=this;b.version=k.VERSION+"";b.timerInterval=1;b.timerID=null;b.startTime=new Date;b.inFrame=!1;b.nfPresent=!1;b.forElement=null;b.props=[];b.rImages=[];b.size=null;b.cookie=!0;b.frameClimbData=null;var n=function(a,b){setTimeout(function(){var b=a,c=(new Date).getTime(),
e=document.readyState,b=null!=b?b:c;"undefined"!==typeof e?"interactive"===e?3E3<=c-b?m(1):n(b):"complete"===e?m(b===c?2:0):n():m(8)},b||250)},q=function(){var a=b.forElement;null==a&&(a=b.forElement=h.imageElems[d]);return a},m=function(c){f(110);if(1!==b.props.sn){b.props.ols=c;b.props["if"]=b.nfPresent?1:0;b.nfPresent&&(c=new E,b.props.sf=c.isSafeFrame()?1:0);b.props.mbl=b.frameClimbData.inMobile?1:0;b.props.ta=b.nfPresent&&!v.isSupported()?"na":0;c=w.getRootDocumentRect("document");b.props.ds=
null==c?"-1x-1":c.getWidth()+"x"+c.getHeight();f(111);c=w.getDocumentRect(window,"document");b.props.dsf=null==c?"-1x-1":c.getWidth()+"x"+c.getHeight();f(112);b.props.vd=b.nfPresent&&!v.isSupported()?0:1;u(!1);if(null!=b.props.x&&null!=b.props.y&&("na"==b.props.x||"na"==b.props.y)){c=q();c=w.getLocationCoords(c,"document",a.position);var e=v.isSupported()?v.getViewPortRect_Viewport():w.getRootDocumentRect("document");null!=c&&(c.isDefined()&&null!=e&&e.isDefined())&&(c=w.getLocationPercentages(c,
e,!0),b.props.x=c.x,b.props.y=c.y)}f(113);if(null!=a.dgVendors){c=a.dgVendors;for(e=0;e<c.length;e++){var d=s[c[e]];b.props[d.propName]=1;b.sendResponse(g.DEFINED[d.actionCode])}}f(114);b.sendResponse(g.DEFINED.LOAD)}},t=function(){var a=function(){try{y.hasFocus&&(x("viewport")&&(b.props.ta+=b.timerInterval),u())}catch(a){b.timerID&&(clearInterval(b.timerID),b.timerID=null)}},c=1E3*b.timerInterval;a();b.timerID=setInterval(a,c)},u=function(a){if(null===a||"boolean"!=typeof a)a=!0;var c=y.hasFocus,
e=x("viewport"),d=x("document");if(c&&(d||e)&&null!==b.props.sn&&0===b.props.sn)b.props.sn=1,a&&b.sendResponse(g.DEFINED.SEEN)},x=function(b){var c=-1,e=-1,d=q();b=w.getLocationCoords(d,b,a.position);d=v.isSupported()?v.getViewPortRect_Viewport():w.getRootDocumentRect("document");null!=b&&(b.isDefined()&&null!=d&&d.isDefined())&&(e=w.getLocationPercentages(b,d,!1),c=e.x,e=e.y);return 0>c||100<c||0>e||100<e?!1:!0},z=function(a,c,e){var d="";void 0===c&&(c=null);void 0===e&&(e=!0);if("function"!=typeof b.props[a]){if(!1!==
e)try{c=encodeURIComponent(c)}catch(f){c=escape(c)}d=a+"="+c+"&"}return d},A=function(c){if(!c)return null;var d;d="?"+z("at",c.type);d+=z("d",c.description);if(c.requiredProps)if(c.requiredProps.constructor==Array){for(var f="",h="",g=[],k=0,g=g.concat(c.requiredProps),g=g.concat(e.QS_ALWAYS),k=0;k<g.length;k++)f=g[k],!e.arrayContains(e.PATHORDER,f)&&"url"!=f.toLowerCase()&&(h=b.props[f],d+=z(f,h));if(c.appendCustomValues)for(f in g=a.passthru,g)g.hasOwnProperty(f)&&(h=g[f],d+=z(f,h,!1))}else return null;
else return d;d+=z("url",b.props.url);return d.substring(0,d.length-1)};this.sendResponse=function(c){f(200);var d=null;if(null===c||null===c.type)return null;var g=new Image;g.border="0";g.height=1;g.width=1;g.vspace=0;g.hspace=0;if(g){b.props.rand=e.generateRandom(999998);b.props.tp=Math.round(((new Date).getTime()-b.startTime.getTime())/1E3);for(var d="/",h=0;h<e.PATHORDER.length;h++)d+=b.props[e.PATHORDER[h]]+"/";d+="1.ver";h=A(c);d=a.protocol+"://"+e.HOSTNAME+d+h;null!=c.logMutator&&"function"==
typeof c.logMutator&&(d=c.logMutator(d,this));null!=d&&(d.length>e.MAX_URL_LENGTH&&(d=d.substring(0,e.MAX_URL_LENGTH)),0<d.length&&(g.src=d,b.rImages.push(g)))}"ol"==c.type.toLowerCase()&&t();return d};f(50);(function(){f(101);b.props.bid=a.bid;b.props.gid=a.gid;b.props.pid=a.pid;b.props.cid=a.cid;b.props.aid=a.aid;b.props.srcid=a.srcid;b.props.advid=a.advid;b.props.sid=e.generateRandom(999998);f(102);var g,h=g=null,k;null!=a&&(null!=a.adSize&&""!=a.adSize)&&(k=a.adSize.split("x"),null!=k&&2===k.length&&
(g=Number(k[0]),h=Number(k[1])));g=new r(g,h);b.size=g;b.props.sz=null!=b.size&&b.size.isDefined()?b.size.getWidth()+"x"+b.size.getHeight():"na";f(103);b.cookie="undefined"!==typeof a.cookie?a.cookie:!0;b.props.nc=!1===b.cookie?1:0;f(104);b.props.csync="undefined"!==typeof a.csync&&!1===a.csync?0:1;b.props.echo=a.echo;b.frameClimbData=frameClimbInfo();b.inFrame=b.frameClimbData.inFrame;b.nfPresent=b.frameClimbData.nonFriendlyPresent;b.props.url=b.frameClimbData.url;b.props.jt=b.frameClimbData.toTop;
b.props.jf=b.frameClimbData.friendLevel;f(105);b.props.ols="na";b.props["if"]="na";b.props.num=d;b.props.sr=e.getScreenRes();b.props.ds="na";b.props.dsf="na";b.props.tz=e.getTimeZone();b.props.sf="na";b.props.vd=0;b.props.sn=0;b.props.tp=0;b.props.ta=0;b.props.x="na";b.props.y="na";b.props.jsv=b.version;for(var l in s)s.hasOwnProperty(l)&&(b.props[s[l].propName]=0);b.props.oc="ADO";f(106);n();f(115);null!=c&&"undefined"!=typeof c&&b.sendResponse(c);f(116)})()};k.VERSION="4.4.2";k.MAX_URL_LENGTH=2048;
k.HOSTNAME="log.dmtry.com";k.PATHORDER="rand bid gid pid cid sid aid srcid advid".split(" ");k.QS_ALWAYS="jf jt jsv oc nc num sr tz url".split(" ");k.sendError=function(a,c){var d=new Image,e="/";if(null!=a)for(var f=k.PATHORDER,b=0;b<f.length;b++)e=null!=a[f[b]]?e+a[f[b]]:e+0,e+="/";d.src="http://"+k.HOSTNAME+e+"1.ver?at=e&d="+escape(c+" ["+C.toString()+"]")+"&jsv="+k.VERSION};k.arrayContains=function(a,c){for(var d=0;d<a.length;d++)if(a[d]==c)return!0;return!1};k.generateRandom=function(a){return Math.floor(Math.random()*
a)+2};k.getScreenRes=function(){try{return screen.width+"x"+screen.height+"x"+screen.colorDepth}catch(a){return"na"}};k.getTimeZone=function(){try{return(new Date).getTimezoneOffset()/60}catch(a){return"na"}};(function(){try{var a=n.parseScriptUrl("http(s)?://(js|log).dmtry.com/antenna2.js");null!=a&&l.AntennaManager.create(a)||k.sendError(a,"Antenna object COULD NOT be created.")}catch(c){k.sendError(null,c.message)}window.addEventListener?(1==l.AntennaManager.antennas.length&&window.addEventListener("unload",
l.AntennaManager.shutdownAntennas,!1),window.addEventListener("focus",y.onfocus,!1),window.addEventListener("blur",y.onblur,!1)):(1==l.AntennaManager.antennas.length&&window.attachEvent("onunload",l.AntennaManager.shutdownAntennas),document.attachEvent("onfocusin",y.onfocus),document.attachEvent("onfocusout",y.onblur))})()}catch(A){try{k.sendError(null,"Global Catch: "+A.name+":"+A.number+": "+A.message)}catch(F){}}})();
